import 'package:example/example.dart';

void main() {
  final userModel = UserModel(id: 1, name: 'John Doe');
  
  // The toEntity() method is automatically generated by omni_mapper
  final userEntity = userModel.toEntity();
  
  print('Successfully mapped to entity!');
  print('Entity ID: ${userEntity.id}');
  print('Entity Name: ${userEntity.name}');
}
