name: example
description: Example project for omni_mapper.
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  omni_mapper:
    path: ../omni_mapper

dev_dependencies:
  build_runner: ^2.4.0
  omni_mapper_generator:
    path: ../omni_mapper_generator

dependency_overrides:
  omni_mapper:
    path: ../omni_mapper
