name: omni_mapper_workspace
publish_to: 'none'

environment:
  sdk: '>=3.5.0 <4.0.0'

workspace:
  - packages/omni_mapper
  - packages/omni_mapper_generator
  - packages/omni_mapper_generator/example
  - packages/example
dev_dependencies:
  lints: ^3.0.0
